create table if not exists public.customers (
 id bigint generated by default as identity primary key,
 created_at timestamptz default now(),
 full_name text not null,
 email text not null,
 phone text,
 plan text,
 start_date date,
 expiration_date date not null,
 status text default 'active',
 amount_paid numeric(10,2),
 notes text
);
alter table public.customers enable row level security;
create policy "signed in read" on public.customers for select to authenticated using (true);
create policy "signed in insert" on public.customers for insert to authenticated with check (true);
create policy "signed in update" on public.customers for update to authenticated using (true) with check (true);
create policy "signed in delete" on public.customers for delete to authenticated using (true);
create table if not exists public.reminder_log(id bigint generated always as identity primary key,customer_id bigint references public.customers(id) on delete cascade,expiration_date date not null,sent_at timestamptz default now(),unique(customer_id,expiration_date));
alter table public.reminder_log enable row level security;
